---
name: Shellcheck

on:
  push:
    paths:
      - 'imei.sh'
      - 'etc/cron.daily/imei'
  pull_request:
    paths:
      - 'imei.sh'
      - 'etc/cron.daily/imei'

jobs:
  ShellCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "imei.sh,etc/cron.daily/imei"
