---
name: TestBuild

on:
  push:
    paths:
      - 'imei.sh'
  pull_request:
    paths:
      - 'imei.sh'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  TestBuild:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: sudo apt-get install wget cmake yasm libde265-dev libx265-dev
      
      - name: Build
        run: sudo bash imei.sh --travis --log-file "build.log" -- && echo "Test build OK"
          
      - name: On failure
        if: ${{ failure() }}
        run: sudo tail -5 build.log
