---
name: Test

on:
  pull_request:
    paths:
      - 'imei.sh'

jobs:
  ShellCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Run Shellcheck
        uses: azohra/shell-linter@v0.4.0
        with:
          path: "imei.sh"

  TestBuild:
    needs: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
      - uses: fauguste/auto-cancellation-running-action@0.1.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Install Dependencies
        run: sudo apt-get install wget cmake yasm libde265-dev libx265-dev

      - name: Build
        run: sudo bash imei.sh --ci --no-sig-verify --log-file "build.log" -- && echo "Test build OK"

      - name: On failure
        if: ${{ failure() }}
        run: sudo tail -5 build.log
