---
name: UpdateReadme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
          
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        
      - name: Update README
        run: |-
          python update_readme.py
          cat README.md
          
      - name: Commit and push if changed
        run: |-
          git add README.md
          git diff
          git config --global user.email "readme-bot@1-2.dev"
          git config --global user.name "README Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
