---
name: UpdateVersionInfo

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Update Version Information
        run: python update_version_info.py

      - name: Commit and push on changes
        run: |-
          git add .
          git diff
          git config --global user.email "33604303+magickwizard@users.noreply.github.com"
          git config --global user.name "magickwizard"
          git commit -m "Updated version information" -a || echo "No changes to commit"
          git push
